[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
evm_version = 'paris'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  optimism = "${OPTIMISM_RPC_URL}"
  arbitrum = "${ARBITRUM_RPC_URL}"
  celo = "${CELO_RPC_URL}"
  linea = "${LINEA_RPC_URL}"

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  optimism = { key = "${API_KEY_OPTIMISM}" }
  arbitrum = { key = "${API_KEY_ARBITRUM}" }
  celo = { key = "${API_KEY_CELO}" }
  linea = { key = "${API_KEY_LINEA}" }
